language: go
sudo: false
go:
- 1.7.x
- 1.8.x
env:
  global:
  - GO15VENDOREXPERIMENT=1
  - TEST_TIMEOUT_SCALE=10
cache:
  directories:
  - vendor
install:
- go get -v github.com/Masterminds/glide
- cd $GOPATH/src/github.com/Masterminds/glide && go install && cd -
- glide install
- go install ./vendor/github.com/mattn/goveralls
script:
- go test -race -v
after_success:
- goveralls -service=travis-ci
notifications:
  slack:
    secure: WclGCBMUEOVHRVvVgcTTkxzKrwgmdKQjOkcW42AeSYGpEgeRnU64we6qILJ6cuTEtYkPjU71V35jZMUaj6JhbaAsXDMHTTcdfPGQ1Hi9dlyKffi//Str3cK/dohXE5q1SIoDiAmG5fz9Z1WrLrf/7cMyH2U+0dznNL5nsQxp5Le0IXwnNqSNqcYXiX+goZsqTyUjPxrZYTaf6TZwFv6qEYP5dbjCh9msqZWqf6uvZJLiXECqUQEZUD/dqU1lGaKj8hhAZ/T51qm5gQctPG2VOUCNtTTjm2GQmVbCmVapFIeHRdY3J1ROX8wedyPXJBnF6qEb6jVSfKtpV4DdLMEM9+eZxuxrv/p0q04M0mYpgS/sFD+pWlK0P7yR88eqaCtZDI+7Q8dQC2SR2gJeCzGgRbiIPuX6x5+rmFLJhyQqtG5AVAlh06GsrfoC0yK9RwxGAsdVdnyIJVcpDvIcRgSsgfLsmizW+DUdd3N3Ir37437B5lKWbHpjCm251FCMnp+03QugMhUtf1ZPtOjShZmFbzC+R/o1Dq/z8UKJOIWPRiSyHPYVExgGHwPzeNaIqTY39mWL9IjNblA25cyIteixSeJ2CY24dJf/CyoaPhqiXKzfz2vi3s08t4TfNrl4P/vuwE7h7QCLPpB4JEfp+epPya3iFBoxmUnKzAHP/xd9ePA=
